- name: update apt cache and install MySQL
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - mysql-server
    - python-pip
    - default-libmysqlclient-dev
  become: True

- name: install MySQL-python module
  pip: name=MySQL-python

- name: start mysql service
  service: name=mysql state=started enabled=yes

- name: set the root password
  mysql_user: >
    name=root 
    password="{{ mysql_root_password }}" 
    check_implicit_admin=yes
    host={{ item }}
    priv="*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_host }}"
    - 127.0.0.1
    - ::1
    - localhost
  become: True

- name: copy root credentials to /root/.my.cnf
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  become: True

- name: delete anonymous user
  mysql_user: name="" state=absent host={{ item }}
  with_items:
    - "{{ ansible_host }}"
    - 127.0.0.1
    - ::1
    - localhost
  become: True

- name: delete test database
  mysql_db: name=test state=absent
  become: True

  
